/* English is the static fallback, including when JavaScript is unavailable. */
(function () {
  "use strict";
  const sl = {
  "Privacy and connections · Safeer": "Zasebnost in povezave · Safeer",
  "Downloads": "Prenosi",
  "How it works": "Kako deluje",
  "Privacy": "Zasebnost",
  "No hidden profiles": "Brez skritih profilov",
  "What privacy means in Safeer.": "Kaj pomeni zasebnost v Safeerju.",
  "Local filters do not mean anonymity. Below is a clear description of the network connections every user should know about.": "Lokalni filtri niso enako kot anonimnost. Spodaj je pregleden opis omrežnih povezav, ki jih mora vsak uporabnik poznati.",
  "This website": "Ta spletna stran",
  "This website includes no analytics, tracking or advertising scripts. It is hosted on GitHub Pages; the host receives standard HTTP network information, including your IP address, when you visit.": "Ta spletna stran ne vključuje analitičnih, sledilnih ali oglaševalskih skript. Gostuje na GitHub Pages; gostitelj ob obisku prejme običajne omrežne podatke HTTP, vključno z naslovom IP.",
  "The browser and visited websites": "Brskalnik in obiskane strani",
  "Websites see your connection's network address and receive their requests, cookies and the information you enter. Your chosen search engine receives search queries. Bookmarks and local settings stay exclusively on your device. Private browsing does not hide your IP address from your internet provider or the website you visit.": "Spletna mesta vidijo omrežni naslov vaše povezave in prejmejo svoje zahteve, piškotke ter podatke, ki jih vnašate. Iskalne poizvedbe prejme izbrani iskalnik. Zaznamki in lokalne nastavitve ostanejo shranjeni izključno na vaši napravi. Zasebni način ne skrije omrežnega naslova IP pred ponudnikom interneta ali obiskano stranjo.",
  "External services": "Zunanje storitve",
  "Depending on the platform and settings, the browser connects to a DNS or DoH provider, filter list sources and the online services you open. Safeer does not operate its own external data collection servers.": "Glede na platformo in nastavitve se brskalnik povezuje s ponudnikom DNS ali DoH, viri seznamov filtrov ter spletnimi storitvami, ki jih odprete. Safeer ne vsebuje lastnih zunanjih strežnikov za zbiranje podatkov.",
  "Ads and threats": "Oglasi in grožnje",
  "Filters use established rules and security lists. They may miss a brand-new threat or occasionally block a legitimate element. The interface does not display unrealistic protection percentages or estimated data savings.": "Filtri uporabljajo preverjena pravila in varnostne sezname. Lahko zgrešijo povsem novo grožnjo ali v redkih primerih blokirajo veljaven element. Vmesnik ne prikazuje nerealnih odstotkov zaščite ali ocenjenih prihrankov prenosa podatkov.",
  "Source code and openness": "Izvorna koda in odprtost",
  "You can find each platform's code on its download page and on GitHub. The project is open source and can be independently reviewed.": "Kodo posamezne platforme najdete na njeni strani za prenos in na GitHubu. Projekt je odprtokoden in omogoča neodvisen pregled delovanja.",
  "Privacy and connections": "Zasebnost in povezave",
  "Report an issue ↗": "Prijavi težavo ↗",
  "An independent open-source project. Project source code is available under Apache 2.0; included dependencies have their own licenses. Safeer is not affiliated with Google, YouTube, Linux Mint or online content providers.": "Neodvisen odprtokodni projekt. Izvorna koda projektov je na voljo pod licenco Apache 2.0; vključene odvisnosti imajo svoje licence. Safeer ni povezan z Googlom, YouTubom, Linux Mintom ali ponudniki spletnih vsebin.",
  "Release status: September 2026.": "Stanje izdaje: september 2026.",
  "Safeer: a browser for Linux Mint, Android and Android TV. Downloads, source code and clearly stated limitations.": "Safeer: brskalnik za Linux Mint, Android in Android TV. Prenosi, izvorna koda in odkrito opisane omejitve.",
  "Main navigation": "Glavna navigacija",
  "Project information · Safeer": "Podatki o projektu · Safeer",
  "What to expect": "Kaj pričakovati",
  "Real information.": "Dejanski podatki.",
  "No invented counters.": "Brez izmišljenih števcev.",
  "We do not publish numbers of active users, prevented threats or time saved without a verifiable source. Package versions, sizes and checksums are on the download pages.": "Ne objavljamo števila aktivnih uporabnikov, preprečenih groženj ali prihranjenega časa brez preverljivega vira. Različice, velikosti in kontrolne vsote paketov so na straneh za prenos.",
  "View downloads →": "Poglej prenose →",
  "An independent project in development. Project source code is available under Apache 2.0; included dependencies have their own licenses. Safeer is not affiliated with Google, YouTube, Linux Mint or online content providers.": "Neodvisen projekt v razvoju. Izvorna koda projektov je na voljo pod licenco Apache 2.0; vključene odvisnosti imajo svoje licence. Safeer ni povezan z Googlom, YouTubom, Linux Mintom ali ponudniki spletnih vsebin.",
  "Information for this release: 8 September 2026. Listed features do not guarantee compatibility with every website.": "Podatki o tej izdaji: 8. september 2026. Navedene funkcije niso jamstvo za delovanje vseh spletnih strani.",
  "Your web. Your Safeer. · Safeer": "Tvoj splet. Tvoj Safeer. · Safeer",
  "Speed · Privacy · Open source": "Hitrost · Zasebnost · Odprta koda",
  "Your web.": "Tvoj splet.",
  "Your Safeer.": "Tvoj Safeer.",
  "A modern, fast and independent browser. Built-in protection against intrusive ads and online threats, without unnecessary clutter — optimized for your computer, phone and smart TV.": "Sodoben, bliskovito hiter in neodvisen brskalnik. Vgrajena zaščita pred vsiljivimi oglasi in spletnimi grožnjami, brez nepotrebne navlake — namensko optimiziran za vaš računalnik, telefon in pametni televizor.",
  "Choose your device": "Izberi svojo napravo",
  "Completely free. No subscriptions or hidden telemetry.": "Popolnoma brezplačno. Brez naročnin in brez skrite telemetrije.",
  "A clear home page with instant access to your favorite sites, without distractions.": "Pregledna domača stran s takojšnjim dostopom do priljubljenih strani brez motenj.",
  "Download Safeer": "Prenesi Safeer",
  "The right version": "Prava različica",
  "for every device.": "za vsako napravo.",
  "Purpose-built apps for three different environments. Choose a package for your device and start browsing faster.": "Namensko prilagojene aplikacije za tri različna okolja. Izberite paket za svojo napravo in začnite brskati hitreje.",
  "Fast and at home on your desktop.": "Bliskovit in domač na namizju.",
  "Native Linux Mint desktop integration, instant startup without flashing, bookmark import and full control over themes.": "Nativna integracija z namizjem Linux Mint, takojšen zagon brez utripanja, uvoz zaznamkov in popoln nadzor nad temami.",
  "Version 1.0.16 · DEB": "Različica 1.0.16 · DEB",
  "Download and details ↗": "Prenos in podrobnosti ↗",
  "Comfortable, light and efficient.": "Udoben, lahek in varčen.",
  "Designed for comfortable one-handed browsing, a responsive tab grid on tablets and minimal battery use.": "Ergonomsko prilagojen za sproščeno brskanje z eno roko, odzivna mreža zavihkov na tablicah ter minimalna poraba baterije.",
  "Version 1.0.11 · APK": "Različica 1.0.11 · APK",
  "Full control on the big screen.": "Popoln nadzor na velikem zaslonu.",
  "Intuitive remote control, precise navigation between items and smooth video playback powered by Media3.": "Intuitivno vodenje z daljincem, natančen premik med vsebinami ter tekoče predvajanje video vsebin z Media3 pogonom.",
  "Version 2.1.81 · APK": "Različica 2.1.81 · APK",
  "Why choose Safeer?": "Zakaj izbrati Safeer?",
  "Faster, cleaner": "Hitrejši, čistejši",
  "and in your hands.": "in v vaših rokah.",
  "Safeer is optimized for each device, delivering responsive performance and a natural user experience.": "Namesto univerzalnega programa je Safeer optimiziran posebej za vsako napravo, kar prinaša izjemno odzivnost in naraven občutek pri uporabi.",
  "Built-in smart protection": "Vgrajena pametna zaščita",
  "Automatic filtering of intrusive ads, dangerous domains and trackers directly in the browser engine for a calmer, safer web.": "Samodejno filtriranje vsiljivih oglasov, nevarnih domen in sledilcev neposredno v jedru brskalnika za mirnejši in varnejši splet.",
  "Adapted to every screen": "Prilagojen vsakemu zaslonu",
  "Fast desktop shortcuts, larger touch targets on mobile and smooth D-Pad navigation between individual items on TV.": "Hitro delo z bližnjicami na namizju, večje površine za dotik na mobilniku ter tekoč D-Pad izbor po posameznih vsebinah na televizorju.",
  "No tracking or subscriptions": "Brez sledenja in brez naročnin",
  "Fully open source, with no hidden telemetry, user profiling or subscriptions. Your bookmarks and data stay safely with you.": "Popolnoma odprta koda brez skrite telemetrije, profiliranja uporabnikov ali naročnin. Vaši zaznamki in podatki ostajajo varno pri vas.",
  "An honest approach": "Iskren pristop",
  "Reliability.": "Zanesljivost.",
  "No empty promises.": "Brez praznih obljub.",
  "Smart filters remove most distractions.": "Pametni filtri odstranijo večino motenj.",
  "We block most ads and known threats, but web systems keep changing, so some ads or special scripts may remain.": "Blokiramo večino oglasov in znanih groženj, vendar se spletni sistemi nenehno spreminjajo, zato nekateri oglasi ali posebne skripte lahko ostanejo.",
  "Adapting to modern video.": "Prilagajanje sodobnemu videu.",
  "We optimize playback across all platforms, but external video platforms regularly update their players.": "Optimiziramo predvajanje na vseh platformah, vendar zunanje video platforme redno posodabljajo svoje predvajalnike.",
  "Standards and sign-in.": "Standardi in prijava.",
  "DRM-protected video streams and some advanced sign-in checks (such as specific Cloudflare checks) may occasionally require an external system.": "Zaščiteni video tokovi z DRM ter nekatere napredne prijave (npr. specifična Cloudflare preverjanja) lahko občasno zahtevajo zunanji sistem.",
  "Privacy without deception.": "Zasebnost brez prevar.",
  "Safeer does not collect your personal data, but it is not a VPN — visited websites receive the network information needed to establish a connection.": "Safeer ne zbira vaših osebnih podatkov, vendar ni VPN — obiskane spletne strani prejmejo omrežne podatke, potrebne za vzpostavitev povezave.",
  "Privacy details.": "Podrobnosti o zasebnosti.",
  "Frequently asked questions": "Pogosta vprašanja",
  "Do I need an account or subscription?": "Ali potrebujem račun ali naročnino?",
  "You do not need an account or subscription to download and use Safeer. All browser features are free and open source.": "Za prenos in uporabo Safeerja ne potrebujete nobenega računa ali naročnine. Vse funkcije brskalnika so brezplačne in odprtokodne.",
  "Does Safeer include paid movies or TV subscriptions?": "Ali Safeer vključuje plačljive filme ali TV naročnine?",
  "No. Safeer is a web browser that opens websites. It does not provide unauthorized access to paid content or replace TV provider subscriptions.": "Ne. Safeer je spletni brskalnik, ki odpira spletne strani. Ne omogoča neavtoriziranega dostopa do plačljivih vsebin in ne nadomešča naročnin na TV ponudnike.",
  "What about security and open source?": "Kako je poskrbljeno za varnost in odprtokodnost?",
  "Each platform has a public GitHub repository where you can inspect the source code, suggest improvements or report a bug.": "Vsaka platforma ima svoj javni repozitorij na GitHubu, kjer lahko preverite izvorno kodo, predlagate izboljšave ali prijavite napako.",
  "An independent open-source project. Project code is available under Apache 2.0; included dependencies have their own licenses. Safeer is not affiliated with Google, YouTube, Linux Mint or external online content providers.": "Neodvisen odprtokodni projekt. Koda projektov je na voljo pod licenco Apache 2.0; vključene odvisnosti imajo svoje licence. Safeer ni povezan z Googlom, YouTubom, Linux Mintom ali zunanjimi ponudniki spletnih vsebin.",
  "Safeer: a modern, fast and independent web browser for Linux Mint, Android and Android TV. Reliable protection and open source.": "Safeer: sodoben, bliskovito hiter in neodvisen spletni brskalnik za Linux Mint, Android in Android TV. Zanesljiva zaščita in odprta koda.",
  "Safeer home page with a search field and favorite sites": "Domača stran Safeerja z iskalnim poljem in priljubljenimi stranmi",
  "Safeer for Android TV": "Safeer za Android TV",
  "A real browser for your TV.": "Pravi brskalnik za vaš televizor.",
  "Built for your remote control. Clear catalog navigation, bookmarks and optimized video playback with a dedicated Media3 engine. For Android TV 9 or later.": "Narejen posebej za daljinec. Pregledno krmarjenje po katalogih, zaznamki in optimizirano video predvajanje z namenskim Media3 pogonom. Za Android TV 9 ali novejši.",
  "Key benefits": "Glavne prednosti",
  "Precise D-Pad navigation:": "Natančno D-Pad vodenje:",
  "Reliably move one poster at a time (tested on rich catalogs such as HydraHD), without skipping rows or unwanted zooming.": "Zanesljivo premikanje po natanko enem plakatu naenkrat (preizkušeno na bogatih katalogih, kot je HydraHD), brez preskakovanja vrstic ali neželenega povečevanja.",
  "Comfortable remote control:": "Udobno upravljanje z daljincem:",
  "Menu bars and dialogs are fully accessible with directional keys and the OK and Back buttons.": "Menijske vrstice in modalna okna so povsem dosegljivi s smernimi tipkami ter gumboma OK in Nazaj.",
  "Powerful Media3 video engine:": "Zmogljiv Media3 video pogon:",
  "Built-in support for modern video streams (DASH, HLS) for smooth playback on the big screen.": "Vgrajena podpora za sodobne video tokove (DASH, HLS) za tekoče predvajanje na velikem zaslonu.",
  "Official TV banner:": "Uradna TV pasica:",
  "A high-resolution landscape banner that fits naturally into the Android TV launcher without distorting the icon.": "Ležeča pasica visoke ločljivosti, ki se naravno vklopi v zaganjalnik Android TV brez popačenja ikone.",
  "Tested performance": "Preverjeno delovanje",
  "Tested and verified on Philips UHD televisions running Android TV 11. Designed for TVs, projectors and TV players running Android TV 9 or later.": "Preizkušeno in potrjeno na televizorjih Philips UHD z Android TV 11. Zasnovano za vse televizorje, projektorje in TV predvajalnike z Android TV 9 ali novejšim.",
  "Installation package": "Namestitveni paket",
  "8 September 2026 · Android TV": "8. september 2026 · Android TV",
  "Download APK ↓": "Prenesi APK ↓",
  "Size": "Velikost",
  "Source code on GitHub ↗": "Izvorna koda na GitHubu ↗",
  "The checksum lets you verify the integrity of the downloaded package.": "Kontrolna vsota zagotavlja celovitost prenesenega paketa.",
  "Installation": "Namestitev",
  "Download the TV APK directly to your TV or transfer it using a USB drive or local network.": "Prenesite TV APK neposredno na televizor ali ga prenesite preko USB ključka / lokalnega omrežja.",
  "Start the installation and confirm the permission in Android TV.": "Zaženite namestitev in potrdite dovoljenje v sistemu Android TV.",
  "The app appears among your installed apps with a full landscape TV banner.": "Aplikacija se pojavi med vašimi nameščenimi aplikacijami s polno ležečo TV pasico.",
  "Limitations and transparency": "Omejitve in preglednost",
  "Safeer makes browsing with a remote comfortable, but does not replace official TV subscriptions or bypass paid content. Protected streams using certain types of DRM may require certified dedicated apps.": "Safeer omogoča udobno brskanje po spletu z daljincem, vendar ne nadomešča uradnih TV naročnin in ne omogoča obhoda plačljivih vsebin. Zaščiteni tokovi z določenimi vrstami DRM morda zahtevajo certificirane namenske aplikacije.",
  "Privacy, data and external connections →": "Zasebnost, podatki in zunanje povezave →",
  "An independent open-source project. Code is available under Apache 2.0. Safeer is not affiliated with YouTube or TV manufacturers.": "Neodvisen odprtokodni projekt. Koda je na voljo pod licenco Apache 2.0. Safeer ni povezan z YouTubom ali proizvajalci televizorjev.",
  "Safeer for Android TV: precise remote navigation, clear catalogs and a powerful Media3 video engine.": "Safeer za Android TV: natančno vodenje z daljincem, čisti katalogi in zmogljiv Media3 video pogon.",
  "Safeer for Linux Mint": "Safeer za Linux Mint",
  "Built natively with GTK3 and WebKit for Linux Mint and Ubuntu. Instant startup without flashing, theme support, bookmark import and a clean user experience.": "Nativno zgrajen z GTK3 in WebKit za Linux Mint in Ubuntu. Takojšen zagon brez utripanja, podpora za teme, uvoz zaznamkov in čista uporabniška izkušnja.",
  "Startup without a white flash:": "Zagon brez belega utripa:",
  "An optimized window transition immediately shows your home page with your chosen desktop theme.": "Optimiziran prehod okna takoj prikaže vašo domačo stran z izbrano temo namizja.",
  "Full native integration:": "Popolna nativna integracija:",
  "Naturally matches Linux Mint's appearance (Mint-Y, dark and light themes), with system shortcuts and fast bookmark import.": "Se naravno zlije z videzom Linux Minta (Mint-Y, temna, svetla tema), podpira sistemske bližnjice in hiter uvoz zaznamkov.",
  "Built-in smart protection:": "Vgrajena pametna zaščita:",
  "Blocks annoying ads and malicious domains directly in the engine for faster loading without heavy extensions.": "Blokiranje nadležnih oglasov in zlonamernih domen neposredno v jedru za hitrejše nalaganje brez težkih razširitev.",
  "Low resource usage:": "Nizka poraba virov:",
  "A lightweight browser without unnecessary background processes or telemetry collection.": "Lahek brskalnik brez nepotrebnih procesov v ozadju in brez zbiranja telemetrije.",
  "Optimized and thoroughly tested on Linux Mint with WebKitGTK. Fast search (Google, DuckDuckGo) and verified stability for everyday browsing.": "Optimizirano in natančno preizkušeno v okolju Linux Mint z WebKitGTK. Hitro iskanje (Google, DuckDuckGo) in preverjena stabilnost pri vsakdanjem brskanju.",
  "8 September 2026 · Linux Mint / Ubuntu": "8. september 2026 · Linux Mint / Ubuntu",
  "Download DEB ↓": "Prenesi DEB ↓",
  "Release notes on GitHub ↗": "Opombe ob izdaji na GitHubu ↗",
  "Source code ↗": "Izvorna koda ↗",
  "Download the DEB installation package.": "Prenesite namestitveni paket DEB.",
  "Install it by double-clicking in the software manager or using the terminal:": "Namestite ga z dvoklikom v upravljalniku programov ali v terminalu:",
  "Launch Safeer Browser from the applications menu.": "Zaženite Safeer Browser iz menija aplikacij.",
  "Download portable package (TAR.GZ)": "Prenos prenosnega paketa (TAR.GZ)",
  "Built-in filters remove most advertising scripts and dangerous domains, but the web keeps evolving, so some ads or special DRM content may require specific external browsers.": "Vgrajeni filtri odstranijo večino oglasnih skript in nevarnih domen, vendar se splet nenehno razvija, zato nekateri oglasi ali posebne DRM vsebine lahko zahtevajo specifične zunanje brskalnike.",
  "An independent open-source project. Source code is available under Apache 2.0. Safeer is not affiliated with Google or Linux Mint.": "Neodvisen odprtokodni projekt. Izvorna koda je na voljo pod licenco Apache 2.0. Safeer ni povezan z Googlom ali Linux Mintom.",
  "Safeer for Linux Mint: a fast, native and secure web browser built with GTK3 and WebKit.": "Safeer za Linux Mint: bliskovit, nativen in varen spletni brskalnik z GTK3 in WebKit.",
  "Safeer for Android": "Safeer za Android",
  "Phone and tablet, one great browser.": "Telefon in tablica, en vrhunski brskalnik.",
  "Comfortable one-handed browsing, a responsive multi-column tab grid on tablets and lightweight performance with minimal battery use. For Android 9 or later.": "Udobno brskanje z eno roko, odzivna večstolpčna mreža zavihkov na tablicah ter lahkotno delovanje z minimalno porabo baterije. Za Android 9 ali novejši.",
  "Ergonomic one-handed design:": "Ergonomska zasnova za eno roko:",
  "Larger touch targets (48 dp) and strategically placed buttons for comfortable thumb operation on modern phones.": "Povečane površine za dotik (48 dp) in strateško postavljeni gumbi za sproščeno upravljanje s palcem na sodobnih telefonih.",
  "Smart tablet adaptation:": "Pametno prilagajanje tablicam:",
  "An automatic multi-column tab layout (3 columns from 600 dp, 4 columns from 840 dp) keeps everything easy to see.": "Samodejni večstolpčni prikaz zavihkov (3 stolpci od 600 dp, 4 stolpci od 840 dp) omogoča izjemno preglednost pri delu.",
  "Battery and resource efficiency:": "Varčevanje z baterijo in viri:",
  "No wasteful processes or constant background polling. The browser runs quickly and preserves your battery.": "Brez potratnih procesov in stalnega preverjanja v ozadju. Brskalnik deluje bliskovito in ohranja vašo baterijo.",
  "Built-in protection:": "Vgrajena zaščita:",
  "Automatic filtering of ads and redirects to dangerous sites for a cleaner, faster web.": "Samodejno filtriranje oglasov in preusmeritev na nevarne strani za čistejši in hitrejši splet.",
  "Natively built and signed APK, tested on smartphones (Samsung Galaxy S25) and tablets (Galaxy Tab A9+). Compatible with devices running Android 9 or later.": "Nativno zgrajen in podpisan APK, preizkušen na pametnih telefonih (Samsung Galaxy S25) in tablicah (Galaxy Tab A9+). Združljiv z napravami z Androidom 9 ali novejšim.",
  "8 September 2026 · Android phone and tablet": "8. september 2026 · Android telefon in tablica",
  "Download the installation APK to your phone or tablet.": "Prenesite namestitveni APK na telefon ali tablico.",
  "Open the file and confirm installation (allow installation from this source if needed).": "Odprite datoteko in potrdite namestitev (po potrebi omogočite namestitev iz tega vira).",
  "Enjoy clean, fast browsing. You do not need to uninstall the app to update it.": "Uživajte v čistem in hitrem brskanju. Ob posodobitvah aplikacije ni treba odstranjevati.",
  "Filtering removes most ads and unwanted elements, but specific website protections may occasionally require another browser. Safeer does not guarantee anonymity or bypass subscriptions.": "Filtriranje odstrani večino oglasov in neželenih elementov, vendar specifične zaščite posameznih spletnih strani lahko občasno zahtevajo alternativni brskalnik. Safeer ne jamči anonimnosti ali obhoda naročnin.",
  "An independent open-source project. Code is available under Apache 2.0. Safeer is not affiliated with Google or online service providers.": "Neodvisen odprtokodni projekt. Koda je na voljo pod licenco Apache 2.0. Safeer ni povezan z Googlom ali ponudniki spletnih storitev.",
  "Safeer for Android: a fast, comfortable and energy-efficient browser for phones and tablets.": "Safeer za Android: hiter, udoben in energijsko varčen brskalnik za telefone in tablične računalnike."
};
  function detectLanguage(browser) {
    const preferred = (browser.languages && browser.languages[0]) || browser.language || 'en';
    return String(preferred).toLowerCase().split(/[-_]/)[0] === 'sl' ? 'sl' : 'en';
  }
  const lang = detectLanguage(navigator);
  document.documentElement.lang = lang;
  if (lang !== 'sl') return;
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    if (['SCRIPT', 'STYLE'].includes(node.parentElement.tagName)) continue;
    const key = node.nodeValue.trim();
    if (Object.prototype.hasOwnProperty.call(sl, key)) {
      node.nodeValue = node.nodeValue.replace(key, sl[key]);
    }
  }
  document.querySelectorAll('[alt], [aria-label], [title], meta[name="description"]').forEach(el => {
    for (const attr of ['alt', 'aria-label', 'title', ...(el.tagName === 'META' ? ['content'] : [])]) {
      const value = el.getAttribute(attr);
      if (Object.prototype.hasOwnProperty.call(sl, value)) el.setAttribute(attr, sl[value]);
    }
  });
})();
